"""rest

Revision ID: a15592cfd069
Revises: 4972eebf3a8d
Create Date: 2022-11-23 13:17:01.311398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15592cfd069'
down_revision = '4972eebf3a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currEpisode', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('recurring', sa.String(), nullable=True),
    sa.Column('caughtUp', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_caughtUp'), 'anime', ['caughtUp'], unique=False)
    op.create_index(op.f('ix_anime_currEpisode'), 'anime', ['currEpisode'], unique=False)
    op.create_index(op.f('ix_anime_id'), 'anime', ['id'], unique=False)
    op.create_index(op.f('ix_anime_notes'), 'anime', ['notes'], unique=False)
    op.create_index(op.f('ix_anime_recurring'), 'anime', ['recurring'], unique=False)
    op.create_index(op.f('ix_anime_title'), 'anime', ['title'], unique=False)
    op.create_table('manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currChapter', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('recurring', sa.String(), nullable=True),
    sa.Column('caughtUp', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_caughtUp'), 'manga', ['caughtUp'], unique=False)
    op.create_index(op.f('ix_manga_currChapter'), 'manga', ['currChapter'], unique=False)
    op.create_index(op.f('ix_manga_id'), 'manga', ['id'], unique=False)
    op.create_index(op.f('ix_manga_notes'), 'manga', ['notes'], unique=False)
    op.create_index(op.f('ix_manga_recurring'), 'manga', ['recurring'], unique=False)
    op.create_index(op.f('ix_manga_title'), 'manga', ['title'], unique=False)
    op.drop_table('mangas')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    op.create_table('mangas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='manga_users_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mangas_pkey')
    )
    op.drop_index(op.f('ix_manga_title'), table_name='manga')
    op.drop_index(op.f('ix_manga_recurring'), table_name='manga')
    op.drop_index(op.f('ix_manga_notes'), table_name='manga')
    op.drop_index(op.f('ix_manga_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_currChapter'), table_name='manga')
    op.drop_index(op.f('ix_manga_caughtUp'), table_name='manga')
    op.drop_table('manga')
    op.drop_index(op.f('ix_anime_title'), table_name='anime')
    op.drop_index(op.f('ix_anime_recurring'), table_name='anime')
    op.drop_index(op.f('ix_anime_notes'), table_name='anime')
    op.drop_index(op.f('ix_anime_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_currEpisode'), table_name='anime')
    op.drop_index(op.f('ix_anime_caughtUp'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
